# Generated by Django 3.2.3 on 2021-07-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCatergoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre de Usuario')),
                ('aPaterno', models.CharField(max_length=25, verbose_name='Apellido Paterno')),
                ('aMaterno', models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido Materno')),
                ('user', models.CharField(max_length=25, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Obra')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Título de Obra')),
                ('price', models.IntegerField(verbose_name='Precio de Obra')),
                ('heigth', models.IntegerField(verbose_name='Alto de Obra')),
                ('width', models.IntegerField(verbose_name='Ancho de Obra')),
                ('year', models.IntegerField(verbose_name='Año de Obra')),
                ('image', models.ImageField(null=True, upload_to='gallery', verbose_name='Imagen de Obra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Autor de Obra')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Estilo de Obra')),
            ],
        ),
    ]
